export const mmkvInit: () => void;

/* auto-generated by NAPI-RS-OHOS */
/* eslint-disable */
export function getFloat(key: string): number


export function getInt(key: string): number


export function init(dir: string): void


export function setFloat(value: number, key: string): void


export function setInt(value: number, key: string): void


