[package]
name = "custom_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.78"
syn = {version = "2.0.48",features = ["full"]}
quote = "1.0.35"

[lib]
proc-macro = true